name: fresh-scs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - flask==3.0.2
    - flask-cors==4.0.0
    - gitpython==3.1.42
    - sentence-transformers==2.2.2
    - chromadb==0.4.14  # Using a newer version that's more compatible
    - python-dotenv==1.0.1
    - pydantic>=2.6.3  # Explicitly setting pydantic version
    - transformers==4.35.2
    - torch==2.1.0
    - typing-extensions>=4.8.0  # Updated to be compatible with pydantic